from rest_framework import generics, permissions
from rest_framework.response import Response
from rest_framework.views import APIView

from .models import EABacktestResult, EADeployment, ExpertAdvisor
from .serializers import (
    EABacktestResultSerializer,
    EACreateSerializer,
    EADeploymentSerializer,
    EAGenerateCodeSerializer,
    ExpertAdvisorSerializer,
)


class ExpertAdvisorListView(generics.ListAPIView):
    serializer_class = ExpertAdvisorSerializer

    def get_queryset(self):
        return ExpertAdvisor.objects.filter(user=self.request.user)


class ExpertAdvisorDetailView(generics.RetrieveAPIView):
    queryset = ExpertAdvisor.objects.all()
    serializer_class = ExpertAdvisorSerializer


class ExpertAdvisorCreateView(APIView):
    permission_classes = [permissions.IsAuthenticated]

    def post(self, request):
        serializer = EACreateSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        from indicators.models import Timeframe
        from trading.models import Symbol

        symbol = Symbol.objects.get(id=serializer.validated_data["symbol"])
        timeframe = Timeframe.objects.get(code=serializer.validated_data["timeframe"])

        ea = ExpertAdvisor.objects.create(
            user=request.user,
            name=serializer.validated_data["name"],
            description=serializer.validated_data.get("description", ""),
            symbol=symbol,
            timeframe=timeframe,
            strategy_type=serializer.validated_data["strategy_type"],
            parameters=serializer.validated_data.get("parameters", {}),
            risk_per_trade=serializer.validated_data.get("risk_per_trade", 2.0),
            use_stop_loss=serializer.validated_data.get("use_stop_loss", True),
            use_take_profit=serializer.validated_data.get("use_take_profit", True),
            ai_generated=True,
        )

        return Response(ExpertAdvisorSerializer(ea).data, status=201)


class EAGenerateCodeView(APIView):
    """Generate MQL5 code for an EA using @minimax"""

    permission_classes = [permissions.IsAuthenticated]

    def post(self, request):
        serializer = EAGenerateCodeSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        ea = ExpertAdvisor.objects.get(id=serializer.validated_data["ea_id"], user=request.user)

        # This would trigger @minimax code generation
        # Placeholder MQL5 code
        mql5_code = f"""//+------------------------------------------------------------------+
//| {ea.name}.mq5
//| Generated by Dutchkem Trading AI - @minimax
//+------------------------------------------------------------------+
#property copyright "Dutchkem Trading AI"
#property version   "1.00"
#property strict

input double RiskPercent = {ea.risk_per_trade};
input bool UseStopLoss = {ea.use_stop_loss};
input bool UseTakeProfit = {ea.use_take_profit};

int OnInit()
{{
   Print("{ea.name} initialized on {ea.symbol.name} {ea.timeframe.code}");
   return(INIT_SUCCEEDED);
}}

void OnTick()
{{
   // Strategy logic here
}}

void OnDeinit(const int reason)
{{
   Print("{ea.name} deinitialized");
}}
"""

        ea.mql5_code = mql5_code
        ea.compiled = False
        ea.save()

        return Response({"ea_id": str(ea.id), "mql5_code": mql5_code, "status": "generated"})


class EABacktestView(APIView):
    """Run backtest for an EA"""

    permission_classes = [permissions.IsAuthenticated]

    def post(self, request, ea_id):
        ea = ExpertAdvisor.objects.get(id=ea_id, user=request.user)

        # This would trigger backtesting via SYNX-MT5-MCP
        return Response({"ea_id": str(ea.id), "status": "backtest_queued"})


class EADeployView(APIView):
    """Deploy EA to MT5"""

    permission_classes = [permissions.IsAuthenticated]

    def post(self, request, ea_id):
        ea = ExpertAdvisor.objects.get(id=ea_id, user=request.user)

        if not ea.compiled:
            return Response({"error": "EA must be compiled first"}, status=400)

        deployment = EADeployment.objects.create(
            ea=ea, mt5_account=request.user.mt5_account, mt5_server=request.user.mt5_server, status="DEPLOYING"
        )

        ea.status = "LIVE"
        ea.deployed_at = deployment.deployed_at
        ea.save()

        return Response(EADeploymentSerializer(deployment).data, status=201)


class EAListView(APIView):
    """Get all EAs for the user"""

    permission_classes = [permissions.IsAuthenticated]

    def get(self, request):
        eas = ExpertAdvisor.objects.filter(user=request.user)
        return Response(ExpertAdvisorSerializer(eas, many=True).data)
