web: cd backend && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --threads 2 --timeout 120
worker: cd backend && celery -A config worker -l info --concurrency=4
beat: cd backend && celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
