# Generated by Django 4.2.30 on 2026-08-27 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signals', '0001_initial'),
        ('trading', '0001_initial'),
        ('indicators', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='trading.symbol'),
        ),
        migrations.AddField(
            model_name='signal',
            name='timeframe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='indicators.timeframe'),
        ),
        migrations.AddField(
            model_name='confluencescore',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confluence_scores', to='trading.symbol'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['symbol', 'timeframe', '-created_at'], name='signals_sig_symbol__140fba_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['signal_type', 'is_active'], name='signals_sig_signal__5c7db4_idx'),
        ),
    ]
