# Generated by Django 4.2.30 on 2026-08-27 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('TRADE', 'Trade Notification'), ('RISK', 'Risk Alert'), ('PAYMENT', 'Payment Notification'), ('SIGNAL', 'Signal Alert'), ('EA', 'EA Notification'), ('SYSTEM', 'System Notification'), ('KYC', 'KYC Notification')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('body_template', models.TextField()),
                ('email_template', models.TextField(blank=True)),
                ('push_template', models.TextField(blank=True)),
                ('sms_template', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'notification templates',
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_trades', models.BooleanField(default=True)),
                ('email_signals', models.BooleanField(default=True)),
                ('email_risk_alerts', models.BooleanField(default=True)),
                ('email_payments', models.BooleanField(default=True)),
                ('push_trades', models.BooleanField(default=True)),
                ('push_signals', models.BooleanField(default=True)),
                ('push_risk_alerts', models.BooleanField(default=True)),
                ('push_payments', models.BooleanField(default=False)),
                ('sms_risk_alerts', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user notification preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('TRADE', 'Trade Notification'), ('RISK', 'Risk Alert'), ('PAYMENT', 'Payment Notification'), ('SIGNAL', 'Signal Alert'), ('EA', 'EA Notification'), ('SYSTEM', 'System Notification'), ('KYC', 'KYC Notification')], max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('data', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_email', models.BooleanField(default=False)),
                ('sent_push', models.BooleanField(default=False)),
                ('sent_sms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
