app = "dutchkem-trading-ai-frontend"
primary_region = "ams"

[build]
  dockerfile = "dutchkem-trading-ai/frontend/Dockerfile.fly"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[http_service.checks]]
  grace_period = "5s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
