# =============================================================================
# Dutchkem Trading AI — Production Settings
# =============================================================================
# Environment variables (set in Render dashboard):
#   DJANGO_SETTINGS_MODULE=config.settings_prod
#   SECRET_KEY=<auto-generated>
#   DEBUG=0
#   DATABASE_URL=<Supabase connection string>
#   REDIS_URL=<Upstash Redis URL>
#   ALLOWED_HOSTS=.onrender.com
#   CORS_ALLOWED_ORIGINS=<Vercel frontend URL>
# =============================================================================

import os
import ssl
from datetime import timedelta
from pathlib import Path

import dj_database_url

# ── Paths ────────────────────────────────────────────────────────────────────

BASE_DIR = Path(__file__).resolve().parent.parent

# ── Core Security ────────────────────────────────────────────────────────────

SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    raise ValueError("SECRET_KEY environment variable is required in production")

DEBUG = False

# Parse ALLOWED_HOSTS from comma-separated string
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "").split(",")
# Always include Render's external hostname
RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME", "")
if RENDER_EXTERNAL_HOSTNAME and RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# ── Applications ─────────────────────────────────────────────────────────────

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "django_filters",
    "drf_yasg",
    "channels",
    "django_celery_beat",
    "django_celery_results",
    "django_otp",
    "django_otp.plugins.otp_totp",
    "django_otp.plugins.otp_static",
    "django_ratelimit",
    # Local
    "accounts",
    "trading",
    "indicators",
    "signals",
    "risk_management",
    "payments",
    "expert_advisors",
    "mcp_integration",
    "market_data",
    "notifications",
    "analytics",
    "referrals",
    "backtesting",
    "ml",
    "gold_edge",
    "audit",
    "scalping",
    "infrastructure",
    "security",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "security.waf.WAFMiddleware",
    "security.zero_trust.ZeroTrustMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django_otp.middleware.OTPMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_ratelimit.middleware.RatelimitMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

# ── Database (Supabase PostgreSQL) ──────────────────────────────────────────

DATABASES = {
    "default": dj_database_url.config(
        conn_max_age=600,
        conn_health_checks=True,
        ssl_require=True,  # Supabase requires SSL
    )
}

# ── Redis (Upstash) ─────────────────────────────────────────────────────────

REDIS_URL = os.environ.get("REDIS_URL", "")

# Upstash Redis uses TLS — configure connection pool with SSL
def _get_redis_url():
    """Upstash Redis URLs need rediss:// for TLS connections."""
    url = REDIS_URL
    if not url:
        return ""
    # Upstash provides redis:// but we need rediss:// for TLS
    if url.startswith("redis://") and "upstash.io" in url:
        url = url.replace("redis://", "rediss://", 1)
    return url

REDIS_URL_TLS = _get_redis_url()

# ── Django Cache (Upstash Redis) ────────────────────────────────────────────

if REDIS_URL_TLS:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL_TLS,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "CONNECTION_POOL_CLASS": "redis.asyncio.ConnectionPool",
                "CONNECTION_POOL_CLASS_KWARGS": {
                    "max_connections": 20,
                    "retry_on_timeout": True,
                    "ssl_cert_reqs": ssl.CERT_NONE,
                    "ssl_check_hostname": False,
                },
                "SERIALIZER": "django_redis.serializers.json.JSONSerializer",
            },
            "KEY_PREFIX": "dutchkem",
            "TIMEOUT": 300,
        },
        "sessions": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL_TLS,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
            "KEY_PREFIX": "dutchkem_sessions",
            "TIMEOUT": 86400,
        },
        "trading": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL_TLS,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
            "KEY_PREFIX": "dutchkem_trading",
            "TIMEOUT": 60,
        },
    }
else:
    # Fallback: local memory cache (not recommended for production)
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        },
    }

# ── Channel Layers (Upstash Redis for WebSockets) ───────────────────────────

if REDIS_URL_TLS:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL_TLS],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }

# ── Celery (Upstash Redis as Broker) ────────────────────────────────────────

if REDIS_URL_TLS:
    CELERY_BROKER_URL = REDIS_URL_TLS
    CELERY_RESULT_BACKEND = "django-db"
else:
    CELERY_BROKER_URL = None
    CELERY_RESULT_BACKEND = None
    CELERY_TASK_ALWAYS_EAGER = True  # Synchronous fallback

CELERY_CACHE_BACKEND = "django-cache"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60

# ── Authentication ──────────────────────────────────────────────────────────

AUTH_USER_MODEL = "accounts.User"

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator", "OPTIONS": {"min_length": 10}},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ── i18n ────────────────────────────────────────────────────────────────────

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# ── Static Files ────────────────────────────────────────────────────────────

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

# WhiteNoise — compressed static files with long-term caching
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = False
WHITENOISE_MAX_AGE = 31536000

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ── REST Framework ──────────────────────────────────────────────────────────

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",
        "user": "1000/hour",
    },
}

# ── JWT ─────────────────────────────────────────────────────────────────────

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "TOKEN_OBTAIN_SERIALIZER": "accounts.serializers.CustomTokenObtainPairSerializer",
}

# ── CORS / CSRF ─────────────────────────────────────────────────────────────

CORS_ALLOWED_ORIGINS = os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",")
# Auto-add Render frontend domain
if RENDER_EXTERNAL_HOSTNAME:
    _backend_url = f"https://{RENDER_EXTERNAL_HOSTNAME}"
    if _backend_url not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(_backend_url)
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")
if RENDER_EXTERNAL_HOSTNAME:
    _backend_url = f"https://{RENDER_EXTERNAL_HOSTNAME}"
    if _backend_url not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_backend_url)

# ── InfluxDB ────────────────────────────────────────────────────────────────

INFLUXDB_URL = os.environ.get("INFLUXDB_URL", "http://localhost:8086")
INFLUXDB_TOKEN = os.environ.get("INFLUXDB_TOKEN", "")
INFLUXDB_ORG = os.environ.get("INFLUXDB_ORG", "dutchkem")
INFLUXDB_BUCKET = os.environ.get("INFLUXDB_BUCKET", "trading_data")

# ── MetaTrader 5 ────────────────────────────────────────────────────────────

MT5_HOST = os.environ.get("MT5_HOST", "127.0.0.1")
MT5_PORT = int(os.environ.get("MT5_PORT", 8082))
MT5_WS_PORT = int(os.environ.get("MT5_WS_PORT", 8081))
MT5_TIMEOUT = int(os.environ.get("MT5_TIMEOUT", 10))
MT5_MAX_RETRIES = int(os.environ.get("MT5_MAX_RETRIES", 5))
MT5_RETRY_DELAY = float(os.environ.get("MT5_RETRY_DELAY", 2.0))
MT5_MCP_URL = os.environ.get("MT5_MCP_URL", "http://localhost:8082")

# ── Trading Config (V6.5 COMPULSORY — dynamically overridden at runtime) ──

TRADING_CONFIG = {
    # ── Risk limits ──────────────────────────────────────────────────
    "MAX_DRAWDOWN": 0.15,
    "MAX_DAILY_LOSS": 0.03,
    "MAX_POSITION_SIZE": 0.02,
    "MAX_OPEN_POSITIONS": 5,
    "MAX_CORRELATION": 0.7,
    "MIN_RISK_REWARD_RATIO": 2.0,

    # ── Profit targets (V6.5 determines these dynamically) ───────────
    "TARGET_DAILY_GROWTH": 0.15,
    "TARGET_WEEKLY_GROWTH": 1.0,
    "TARGET_MONTHLY_GROWTH": 4.2,
    "TARGET_ANNUAL_GROWTH": 50.0,
    "DAILY_LOSS_LIMIT": 2.0,
    "MAX_DAILY_TRADES": 10,
    "PROFIT_TARGET_SOURCE": "V6.5_ORCHESTRATOR",
}

# ── Rate Limiting ───────────────────────────────────────────────────────────

RATELIMIT_USE_CACHE = "default"
RATELIMIT_FAIL_OPEN = True

# ── Security Headers (Production) ───────────────────────────────────────────

SECURE_SSL_REDIRECT = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
X_FRAME_OPTIONS = "DENY"

# ── Logging ─────────────────────────────────────────────────────────────────

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": True,
        },
        "trading": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "payments": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "signals": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "risk_management": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "infrastructure": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "ml": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "scalping": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# ── Health Check ────────────────────────────────────────────────────────────

HEALTH_CHECK_ENABLED = True
HEALTH_CHECK_TIMEOUT = 10
