# Generated by Django 4.2.30 on 2026-08-27 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
        ('trading', '0001_initial'),
        ('indicators', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsentiment',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiments', to='trading.symbol'),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_data', to='trading.symbol'),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='timeframe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_data', to='indicators.timeframe'),
        ),
        migrations.AddField(
            model_name='liveprice',
            name='symbol',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_price', to='trading.symbol'),
        ),
        migrations.AddIndex(
            model_name='marketdata',
            index=models.Index(fields=['symbol', 'timeframe', '-timestamp'], name='market_data_symbol__57030f_idx'),
        ),
    ]
