# Generated by Django 4.2.30 on 2026-08-27 09:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EABacktestResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('final_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_return', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_drawdown', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sharpe_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_trades', models.IntegerField()),
                ('winning_trades', models.IntegerField()),
                ('losing_trades', models.IntegerField()),
                ('profit_factor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('equity_curve', models.JSONField(default=list)),
                ('trade_history', models.JSONField(default=list)),
                ('parameters_used', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EADeployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mt5_account', models.CharField(max_length=50)),
                ('mt5_server', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('DEPLOYING', 'Deploying'), ('ACTIVE', 'Active'), ('STOPPED', 'Stopped'), ('ERROR', 'Error')], max_length=20)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('logs', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-deployed_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpertAdvisor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('status', models.CharField(choices=[('INACTIVE', 'Inactive'), ('BACKTESTING', 'Backtesting'), ('OPTIMIZING', 'Optimizing'), ('LIVE', 'Live'), ('PAUSED', 'Paused'), ('ERROR', 'Error')], default='INACTIVE', max_length=20)),
                ('strategy_type', models.CharField(max_length=50)),
                ('parameters', models.JSONField(default=dict)),
                ('risk_per_trade', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('max_positions', models.IntegerField(default=1)),
                ('use_stop_loss', models.BooleanField(default=True)),
                ('use_take_profit', models.BooleanField(default=True)),
                ('trailing_stop', models.BooleanField(default=False)),
                ('trailing_stop_pips', models.IntegerField(default=0)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sharpe_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('mql5_code', models.TextField(blank=True)),
                ('compiled', models.BooleanField(default=False)),
                ('mt5_ticket', models.CharField(blank=True, max_length=50)),
                ('ai_generated', models.BooleanField(default=False)),
                ('backtest_results', models.JSONField(default=dict)),
                ('optimization_history', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
