# Generated by Django 4.2.30 on 2026-08-27 09:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('indicator_type', models.CharField(choices=[('TREND', 'Trend'), ('MOMENTUM', 'Momentum'), ('VOLATILITY', 'Volatility'), ('VOLUME', 'Volume'), ('OSCILLATOR', 'Oscillator'), ('CUSTOM', 'Custom')], max_length=20)),
                ('description', models.TextField()),
                ('formula', models.TextField(blank=True)),
                ('default_parameters', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'indicator categories',
            },
        ),
        migrations.CreateModel(
            name='Timeframe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('minutes', models.IntegerField()),
                ('strategy_type', models.CharField(max_length=50)),
                ('risk_level', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM_HIGH', 'Medium-High'), ('MEDIUM', 'Medium'), ('MEDIUM_LOW', 'Medium-Low'), ('LOW_MEDIUM', 'Low-Medium'), ('LOW', 'Low')], max_length=20)),
                ('target_pips_min', models.IntegerField()),
                ('target_pips_max', models.IntegerField()),
                ('stop_loss_min', models.IntegerField()),
                ('stop_loss_max', models.IntegerField()),
                ('win_rate_target_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('win_rate_target_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('risk_reward_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'timeframes',
                'ordering': ['minutes'],
            },
        ),
        migrations.CreateModel(
            name='TimeframeIndicatorConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('parameters', models.JSONField(default=dict)),
                ('priority', models.IntegerField(default=0)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeframe_configs', to='indicators.indicator')),
                ('timeframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_configs', to='indicators.timeframe')),
            ],
            options={
                'ordering': ['-priority', 'indicator__name'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('value', models.JSONField()),
                ('signal', models.CharField(choices=[('STRONG_BUY', 'Strong Buy'), ('BUY', 'Buy'), ('NEUTRAL', 'Neutral'), ('SELL', 'Sell'), ('STRONG_SELL', 'Strong Sell')], default='NEUTRAL', max_length=20)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='indicators.indicator')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
