# Generated by Django 4.2.30 on 2026-08-29 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0001_initial'),
        ('indicators', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldEdgeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default Gold Edge', max_length=100)),
                ('momentum_weight', models.DecimalField(decimal_places=2, default=0.3, max_digits=4)),
                ('trend_weight', models.DecimalField(decimal_places=2, default=0.3, max_digits=4)),
                ('volatility_weight', models.DecimalField(decimal_places=2, default=0.2, max_digits=4)),
                ('dxy_correlation_weight', models.DecimalField(decimal_places=2, default=0.2, max_digits=4)),
                ('atr_period', models.IntegerField(default=14)),
                ('ema_period', models.IntegerField(default=21)),
                ('atr_multipliers', models.JSONField(default=list, help_text='ATR multiplier layers, e.g. [0.5, 1.0, 1.5, 2.0]')),
                ('atr_ratio_min', models.DecimalField(decimal_places=2, default=0.15, max_digits=4)),
                ('atr_ratio_max', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('min_gec_score', models.DecimalField(decimal_places=2, default=0.5, help_text='Minimum GEC composite score to consider entry (-1 to +1)', max_digits=4)),
                ('min_combined_score', models.DecimalField(decimal_places=2, default=0.6, help_text='Minimum combined matrix score for high-probability entry', max_digits=4)),
                ('risk_per_trade', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('sl_atr_multiplier', models.DecimalField(decimal_places=2, default=2.0, max_digits=4)),
                ('tp_atr_multiplier', models.DecimalField(decimal_places=2, default=3.0, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_edge_configs', to='trading.symbol')),
                ('timeframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_edge_configs', to='indicators.timeframe')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gold_edge_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('symbol', 'timeframe')},
            },
        ),
        migrations.CreateModel(
            name='GoldEdgeBacktest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('initial_balance', models.DecimalField(decimal_places=2, default=10000, max_digits=20)),
                ('final_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_pnl_percent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('profit_factor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sharpe_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('parameters', models.JSONField(default=dict)),
                ('trades', models.JSONField(default=list)),
                ('equity_curve', models.JSONField(default=list)),
                ('gec_scores_over_time', models.JSONField(default=list, help_text='GEC composite score at each bar for analysis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backtests', to='gold_edge.goldedgeconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_edge_backtests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoldEdgeSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short'), ('NEUTRAL', 'Neutral')], default='NEUTRAL', max_length=10)),
                ('gec_score', models.DecimalField(decimal_places=4, default=0, help_text='Gold Edge Composite score (-1 to +1)', max_digits=5)),
                ('combined_matrix_score', models.DecimalField(decimal_places=4, default=0, help_text='Final matrix score combining GEC + ATR borders + ATR filter', max_digits=5)),
                ('momentum_score', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('trend_score', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('volatility_score', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('dxy_correlation_score', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('atr_border_layer', models.IntegerField(default=0, help_text='Which ATR border layer the price is in (0=innermost, 3=outermost)')),
                ('atr_ratio', models.DecimalField(decimal_places=4, default=0, help_text='Current ATR / ATR SMA ratio', max_digits=6)),
                ('atr_filter_pass', models.BooleanField(default=False, help_text='Whether ATR ratio is within the ideal entry range')),
                ('entry_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('risk_reward_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('confidence', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('generated_by', models.CharField(default='gold_edge_engine', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='gold_edge.goldedgeconfig')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_edge_signals', to='trading.symbol')),
                ('timeframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_edge_signals', to='indicators.timeframe')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['symbol', 'timeframe', '-created_at'], name='gold_edge_g_symbol__57a193_idx'), models.Index(fields=['direction', 'is_active'], name='gold_edge_g_directi_d5a3f6_idx')],
            },
        ),
    ]
