from typing import Any, Dict, Optional
from datetime import datetime


class MQL5CodeGenerator:
    """
    Generate MQL5 Expert Advisor code from trading strategies.
    Supports ML-enhanced EA generation with regime detection.
    """

    TIMEFRAMES = {
        "M5": "PERIOD_M5",
        "M15": "PERIOD_M15",
        "M30": "PERIOD_M30",
        "H1": "PERIOD_H1",
        "H2": "PERIOD_H2",
        "H4": "PERIOD_H4",
    }

    def generate_ea(
        self,
        name: str,
        symbol: str,
        timeframe: str,
        strategy_type: str,
        parameters: Dict[str, Any],
        risk_per_trade: float = 1.0,
        use_stop_loss: bool = True,
        use_take_profit: bool = True,
        use_trailing_stop: bool = False,
        trailing_stop_pips: int = 0,
        use_ml: bool = True,
        use_regime_detection: bool = True,
    ) -> str:
        mt5_timeframe = self.TIMEFRAMES.get(timeframe, "PERIOD_H1")

        if use_ml or use_regime_detection:
            return self._generate_ml_ea(
                name, symbol, timeframe, mt5_timeframe, strategy_type,
                parameters, risk_per_trade, use_stop_loss, use_take_profit,
                use_trailing_stop, trailing_stop_pips, use_ml, use_regime_detection,
            )

        return self._generate_basic_ea(
            name, symbol, timeframe, mt5_timeframe, strategy_type,
            parameters, risk_per_trade, use_stop_loss, use_take_profit,
            use_trailing_stop, trailing_stop_pips,
        )

    def _generate_ml_ea(
        self, name, symbol, timeframe, mt5_timeframe, strategy_type,
        parameters, risk_per_trade, use_sl, use_tp, use_trail, trail_pips,
        use_ml, use_regime,
    ) -> str:
        import os
        template_path = os.path.join(
            os.path.dirname(__file__), "templates", "ml_ea_template.mq5"
        )
        try:
            with open(template_path, "r") as f:
                code = f.read()
            code = code.replace("DutchkemTradingAI_ML", name)
            code = code.replace("#property version   \"2.00\"", f"#property version   \"1.00\"")
            return code
        except FileNotFoundError:
            return self._generate_basic_ea(
                name, symbol, timeframe, mt5_timeframe, strategy_type,
                parameters, risk_per_trade, use_sl, use_tp, use_trail, trail_pips,
            )

    def _generate_basic_ea(
        self, name, symbol, timeframe, mt5_timeframe, strategy_type,
        parameters, risk_per_trade, use_sl, use_tp, use_trail, trail_pips,
    ) -> str:
        header = self._generate_header(name, symbol, timeframe, strategy_type)
        inputs = self._generate_inputs(
            parameters, risk_per_trade, use_sl, use_tp, use_trail, trail_pips,
        )
        indicators = self._generate_indicators(strategy_type, parameters)
        on_init = self._generate_on_init(strategy_type)
        on_tick = self._generate_on_tick(
            symbol, mt5_timeframe, strategy_type, parameters, use_sl, use_tp, use_trail,
        )
        helpers = self._generate_helpers()

        return f"""{header}

{inputs}

// Indicator buffers
{indicators}

//+------------------------------------------------------------------+
//| Expert initialization function                                     |
//+------------------------------------------------------------------+
int OnInit()
{{
{on_init}
   return(INIT_SUCCEEDED);
}}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                   |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{{
   Print("{name} deinitialized. Reason: ", reason);
}}

//+------------------------------------------------------------------+
//| Expert tick function                                               |
//+------------------------------------------------------------------+
void OnTick()
{{
{on_tick}
}}

{helpers}
"""

    def _generate_header(self, name, symbol, timeframe, strategy_type):
        return f"""//+------------------------------------------------------------------+
//| {name}.mq5
//| Generated by Dutchkem Trading AI
//| Strategy: {strategy_type.title()} on {timeframe}
//| Symbol: {symbol}
//| Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
//+------------------------------------------------------------------+
#property copyright "Dutchkem Trading AI"
#property link      "https://dutchkem.com"
#property version   "1.00"
#property strict"""

    def _generate_inputs(self, parameters, risk_per_trade, use_sl, use_tp, use_trail, trail_pips):
        inputs = f"""
//+------------------------------------------------------------------+
//| Input Parameters                                                  |
//+------------------------------------------------------------------+
input double RiskPercent = {risk_per_trade};
input bool   UseStopLoss = {use_sl};
input bool   UseTakeProfit = {use_tp};
input bool   UseTrailingStop = {use_trail};
input int    TrailingStopPips = {trail_pips};
input int    MagicNumber = 123456;
input int    Slippage = 3;"""

        for key, value in parameters.items():
            if isinstance(value, (int, float)):
                inputs += f"\ninput double {key.title()} = {value};"

        return inputs

    def _generate_indicators(self, strategy_type, parameters):
        return """int handle_rsi, handle_macd, handle_bb, handle_ema_fast, handle_ema_slow;
double buffer_rsi[], buffer_macd[], buffer_signal[], buffer_bb_upper[], buffer_bb_middle[], buffer_bb_lower[];
double buffer_ema_fast[], buffer_ema_slow[];"""

    def _generate_on_init(self, strategy_type):
        return f"""   handle_rsi = iRSI(_Symbol, PERIOD_CURRENT, 14, PRICE_CLOSE);
   handle_macd = iMACD(_Symbol, PERIOD_CURRENT, 12, 26, 9, PRICE_CLOSE);
   handle_bb = iBands(_Symbol, PERIOD_CURRENT, 20, 0, 2.0, PRICE_CLOSE);
   handle_ema_fast = iMA(_Symbol, PERIOD_CURRENT, 5, 0, MODE_EMA, PRICE_CLOSE);
   handle_ema_slow = iMA(_Symbol, PERIOD_CURRENT, 10, 0, MODE_EMA, PRICE_CLOSE);

   if(handle_rsi == INVALID_HANDLE || handle_macd == INVALID_HANDLE)
   {{
      Print("Failed to initialize indicators!");
      return(INIT_FAILED);
   }}

   Print("{strategy_type.title()} EA initialized successfully");"""

    def _generate_on_tick(self, symbol, timeframe, strategy_type, parameters, use_sl, use_tp, use_trail):
        return f"""   static datetime lastBarTime = 0;
   datetime currentBarTime = iTime(_Symbol, {timeframe}, 0);
   if(lastBarTime == currentBarTime) return;
   lastBarTime = currentBarTime;

   double rsi = GetIndicatorValue(handle_rsi, 0);
   double macdMain = GetIndicatorValue(handle_macd, 0);
   double macdSignal = GetIndicatorValue(handle_macd, 1);
   double bbUpper = GetIndicatorValue(handle_bb, 1);
   double bbMiddle = GetIndicatorValue(handle_bb, 0);
   double bbLower = GetIndicatorValue(handle_bb, 2);
   double emaFast = GetIndicatorValue(handle_ema_fast, 0);
   double emaSlow = GetIndicatorValue(handle_ema_slow, 0);

   if(HasOpenPosition(_Symbol, MagicNumber)) {{
      {"ManageTrailingStop();" if use_trail else ""}
      return;
   }}

   int signal = 0;

   if(rsi < 30 && macdMain > macdSignal && emaFast > emaSlow) {{
      signal = 1;
   }}
   else if(rsi > 70 && macdMain < macdSignal && emaFast < emaSlow) {{
      signal = -1;
   }}

   if(signal != 0) {{
      ExecuteTrade(signal, RiskPercent);
   }}"""

    def _generate_helpers(self):
        return """//+------------------------------------------------------------------+
//| Get indicator value                                               |
//+------------------------------------------------------------------+
double GetIndicatorValue(int handle, int buffer, int shift = 0)
{
   double value[];
   ArraySetAsSeries(value, true);
   if(CopyBuffer(handle, buffer, shift, 1, value) > 0)
      return value[0];
   return 0;
}

//+------------------------------------------------------------------+
//| Check if has open position                                         |
//+------------------------------------------------------------------+
bool HasOpenPosition(string symbol, int magicNumber)
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(PositionSelectByTicket(ticket))
      {
         if(PositionGetString(POSITION_SYMBOL) == symbol &&
            PositionGetInteger(POSITION_MAGIC) == magicNumber)
            return true;
      }
   }
   return false;
}

//+------------------------------------------------------------------+
//| Execute trade                                                     |
//+------------------------------------------------------------------+
void ExecuteTrade(int signal, double riskPercent)
{
   double accountEquity = AccountInfoDouble(ACCOUNT_EQUITY);
   double riskAmount = accountEquity * riskPercent / 100.0;

   double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);

   double slDistance = 50 * point;
   double positionSize = NormalizeDouble(riskAmount / (slDistance / tickSize * tickValue), 2);

   double minLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maxLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   double lotStep = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);

   positionSize = MathFloor(positionSize / lotStep) * lotStep;
   positionSize = MathMax(minLot, MathMin(maxLot, positionSize));

   double price = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double sl = 0, tp = 0;

   if(signal == 1)
   {
      price = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      sl = price - slDistance;
      tp = price + slDistance * 2;
   }
   else
   {
      sl = price + slDistance;
      tp = price - slDistance * 2;
   }

   MqlTradeRequest request = {};
   MqlTradeResult result = {};

   request.action = TRADE_ACTION_DEAL;
   request.symbol = _Symbol;
   request.volume = positionSize;
   request.type = signal == 1 ? ORDER_TYPE_BUY : ORDER_TYPE_SELL;
   request.price = signal == 1 ? SymbolInfoDouble(_Symbol, SYMBOL_ASK) : SymbolInfoDouble(_Symbol, SYMBOL_BID);
   request.sl = sl;
   request.tp = tp;
   request.deviation = 3;
   request.magic = MagicNumber;
   request.comment = "Dutchkem AI";

   if(!OrderSend(request, result))
      Print("OrderSend failed: ", GetLastError());
   else
      Print("Order executed successfully. Ticket: ", result.order);
}

//+------------------------------------------------------------------+
//| Manage trailing stop                                              |
//+------------------------------------------------------------------+
void ManageTrailingStop()
{
   double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   double trailingStop = TrailingStopPips * point;

   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(PositionSelectByTicket(ticket))
      {
         if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
         if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;

         double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
         double currentSL = PositionGetDouble(POSITION_SL);
         double currentTP = PositionGetDouble(POSITION_TP);
         long posType = PositionGetInteger(POSITION_TYPE);

         if(posType == POSITION_TYPE_BUY)
         {
            double newSL = SymbolInfoDouble(_Symbol, SYMBOL_BID) - trailingStop;
            if(newSL > currentSL && newSL > openPrice)
            {
               MqlTradeRequest request = {};
               MqlTradeResult result = {};
               request.action = TRADE_ACTION_SLTP;
               request.position = ticket;
               request.symbol = _Symbol;
               request.sl = newSL;
               request.tp = currentTP;
               OrderSend(request, result);
            }
         }
         else if(posType == POSITION_TYPE_SELL)
         {
            double newSL = SymbolInfoDouble(_Symbol, SYMBOL_ASK) + trailingStop;
            if(newSL < currentSL && newSL < openPrice)
            {
               MqlTradeRequest request = {};
               MqlTradeResult result = {};
               request.action = TRADE_ACTION_SLTP;
               request.position = ticket;
               request.symbol = _Symbol;
               request.sl = newSL;
               request.tp = currentTP;
               OrderSend(request, result);
            }
         }
      }
   }
}"""


mql5_generator = MQL5CodeGenerator()
