# Generated by Django 4.2.30 on 2026-08-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentgateway',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='api_secret',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='webhook_secret',
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='supported_channels',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='supported_currencies',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='transaction',
            name='channel',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='korapay_ref',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='name',
            field=models.CharField(choices=[('KORAPAY', 'Korapay'), ('PAYSTACK', 'Paystack'), ('FLUTTERWAVE', 'Flutterwave'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['korapay_ref'], name='payments_tr_korapay_437258_idx'),
        ),
    ]
