//+------------------------------------------------------------------+
//| DutchkemTradingAI_ML.mq5                                        |
//| ML-Enhanced Expert Advisor with Regime Detection                 |
//| Generated by Dutchkem Trading AI                                 |
//+------------------------------------------------------------------+
#property copyright "Dutchkem Trading AI"
#property link      "https://dutchkem.com"
#property version   "2.00"
#property strict

#include <Trade/Trade.mqh>

//+------------------------------------------------------------------+
//| Input Parameters                                                  |
//+------------------------------------------------------------------+
input group "=== Risk Management ==="
input double MaxRiskPerTrade     = 1.0;     // Risk per trade (%)
input double MaxDailyLoss        = 2.0;     // Max daily loss (%)
input double MaxDrawdown         = 15.0;    // Max drawdown (%)
input int    MaxOpenTrades       = 5;       // Max concurrent positions
input int    MaxDailyTrades      = 8;       // Max trades per day
input double DailyTargetConservative = 0.80; // Conservative daily target (%)
input double DailyTargetModerate     = 1.45; // Moderate daily target (%)
input double DailyTargetAggressive   = 2.20; // Aggressive daily target (%)
input int    TargetProfile      = 1;        // Target profile (0=Cons, 1=Mod, 2=Aggr)

input group "=== ML Integration ==="
input bool   UseMLPrediction    = true;     // Enable ML predictions
input double MinConfidence      = 65.0;     // Min ML confidence (%)
input string ML_API_URL         = "http://localhost:8000/api/v1/ml/predict/";
input int    ML_API_TIMEOUT     = 5000;     // API timeout (ms)

input group "=== Regime Detection ==="
input bool   UseRegimeDetection = true;     // Enable regime detection
input int    RegimeCheckBars    = 100;      // Bars for regime calculation
input string RegimeAPI_URL      = "http://localhost:8000/api/v1/ml/regime/";

input group "=== Strategy Parameters ==="
input int    MagicNumber        = 123456;   // Magic number
input int    Slippage           = 3;        // Slippage (points)

input group "=== Indicator Parameters ==="
input int    RSI_Period         = 14;       // RSI period
input int    MACD_Fast          = 12;       // MACD fast
input int    MACD_Slow          = 26;       // MACD slow
input int    MACD_Signal        = 9;        // MACD signal
input int    BB_Period          = 20;       // Bollinger period
input double BB_Deviation       = 2.0;      // Bollinger deviation
input int    ATR_Period         = 14;       // ATR period
input int    ADX_Period         = 14;       // ADX period
input int    EMA_Fast           = 5;        // Fast EMA
input int    EMA_Slow           = 20;       // Slow EMA

//+------------------------------------------------------------------+
//| Enumerations                                                       |
//+------------------------------------------------------------------+
enum ENUM_MARKET_REGIME {
   REGIME_STRONG_TRENDING,
   REGIME_WEAK_TRENDING,
   REGIME_RANGING,
   REGIME_VOLATILE,
   REGIME_NEWS_DRIVEN,
   REGIME_LOW_LIQUIDITY
};

enum ENUM_STRATEGY_TYPE {
   STRAT_TREND_FOLLOWING,
   STRAT_MOMENTUM,
   STRAT_MEAN_REVERSION,
   STRAT_BREAKOUT,
   STRAT_SCALPING,
   STRAT_NONE
};

enum ENUM_SIGNAL_DIR {
   DIR_NONE,
   DIR_BUY,
   DIR_SELL
};

//+------------------------------------------------------------------+
//| Structures                                                         |
//+------------------------------------------------------------------+
struct MlPrediction {
   string direction;
   double confidence;
   string regime;
   double regime_confidence;
   bool   should_trade;
};

struct TradeSignal {
   ENUM_SIGNAL_DIR direction;
   ENUM_MARKET_REGIME regime;
   ENUM_STRATEGY_TYPE strategy;
   double entry_price;
   double stop_loss;
   double take_profit;
   double volume;
   double confidence;
};

struct DailyStats {
   double pnl;
   int    trade_count;
   double peak_equity;
   datetime last_date;
   bool   halted;
   string halt_reason;
};

//+------------------------------------------------------------------+
//| Global Variables                                                   |
//+------------------------------------------------------------------+
CTrade trade;
DailyStats daily;

int handle_rsi, handle_macd_main, handle_macd_signal;
int handle_bb, handle_atr, handle_adx;
int handle_ema_fast, handle_ema_slow;

//+------------------------------------------------------------------+
//| Expert initialization function                                     |
//+------------------------------------------------------------------+
int OnInit() {
   trade.SetExpertMagicNumber(MagicNumber);
   trade.SetDeviationInPoints(Slippage);
   trade.SetTypeFilling(ORDER_FILLING_IOC);

   handle_rsi = iRSI(_Symbol, PERIOD_CURRENT, RSI_Period, PRICE_CLOSE);
   handle_macd_main = iMACD(_Symbol, PERIOD_CURRENT, MACD_Fast, MACD_Slow, MACD_Signal, PRICE_CLOSE);
   handle_macd_signal = iMACD(_Symbol, PERIOD_CURRENT, MACD_Fast, MACD_Slow, MACD_Signal, PRICE_CLOSE);
   handle_bb = iBands(_Symbol, PERIOD_CURRENT, BB_Period, 0, BB_Deviation, PRICE_CLOSE);
   handle_atr = iATR(_Symbol, PERIOD_CURRENT, ATR_Period);
   handle_adx = iADX(_Symbol, PERIOD_CURRENT, ADX_Period);
   handle_ema_fast = iMA(_Symbol, PERIOD_CURRENT, EMA_Fast, 0, MODE_EMA, PRICE_CLOSE);
   handle_ema_slow = iMA(_Symbol, PERIOD_CURRENT, EMA_Slow, 0, MODE_EMA, PRICE_CLOSE);

   if(handle_rsi == INVALID_HANDLE || handle_macd_main == INVALID_HANDLE ||
      handle_bb == INVALID_HANDLE || handle_atr == INVALID_HANDLE || handle_adx == INVALID_HANDLE) {
      Print("Failed to initialize indicators!");
      return(INIT_FAILED);
   }

   daily.peak_equity = AccountInfoDouble(ACCOUNT_EQUITY);
   daily.last_date = StringToTime(TimeToString(TimeCurrent(), TIME_DATE));
   daily.pnl = 0;
   daily.trade_count = 0;
   daily.halted = false;
   daily.halt_reason = "";

   Print("Dutchkem Trading AI EA v2.0 initialized");
   Print("Account Equity: ", DoubleToString(daily.peak_equity, 2));
   Print("Target Profile: ", EnumToString((ENUM_ACCOUNT_TRADE_MODE)TargetProfile));

   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                   |
//+------------------------------------------------------------------+
void OnDeinit(const int reason) {
   IndicatorRelease(handle_rsi);
   IndicatorRelease(handle_macd_main);
   IndicatorRelease(handle_bb);
   IndicatorRelease(handle_atr);
   IndicatorRelease(handle_adx);
   IndicatorRelease(handle_ema_fast);
   IndicatorRelease(handle_ema_slow);
   Print("Dutchkem Trading AI EA deinitialized. Reason: ", reason);
}

//+------------------------------------------------------------------+
//| Expert tick function (CORE LOOP)                                  |
//+------------------------------------------------------------------+
void OnTick() {
   ResetDailyIfNeeded();

   if(daily.halted) {
      ManageExistingPositions();
      return;
   }

   if(!PassRiskChecks()) return;

   ENUM_MARKET_REGIME regime = DetectMarketRegime();

   MlPrediction mlPred;
   if(UseMLPrediction) {
      mlPred = GetMLPrediction();
      if(mlPred.confidence < MinConfidence) {
         ManageExistingPositions();
         return;
      }
   } else {
      mlPred.direction = "NEUTRAL";
      mlPred.confidence = 0;
      mlPred.regime = "unknown";
      mlPred.should_trade = true;
   }

   ENUM_STRATEGY_TYPE strategy = SelectStrategy(regime);

   if(strategy == STRAT_NONE) {
      ManageExistingPositions();
      return;
   }

   if(!mlPred.should_trade && UseMLPrediction) {
      ManageExistingPositions();
      return;
   }

   if(HasOpenPosition()) {
      ManageExistingPositions();
      return;
   }

   TradeSignal signal = GenerateSignal(strategy, regime, mlPred);

   if(signal.direction == DIR_NONE) return;

   if(!ValidateSignal(signal)) return;

   ExecuteTrade(signal);

   ManageExistingPositions();
}

//+------------------------------------------------------------------+
//| Reset daily counters                                              |
//+------------------------------------------------------------------+
void ResetDailyIfNeeded() {
   datetime currentDate = StringToTime(TimeToString(TimeCurrent(), TIME_DATE));
   if(currentDate > daily.last_date) {
      daily.pnl = 0;
      daily.trade_count = 0;
      daily.halted = false;
      daily.halt_reason = "";
      daily.last_date = currentDate;
      Print("Daily counters reset. New trading day.");
   }
}

//+------------------------------------------------------------------+
//| Risk management checks                                            |
//+------------------------------------------------------------------+
bool PassRiskChecks() {
   double equity = AccountInfoDouble(ACCOUNT_EQUITY);

   if(equity > daily.peak_equity) daily.peak_equity = equity;

   double drawdown = (daily.peak_equity - equity) / daily.peak_equity * 100.0;
   if(drawdown >= MaxDrawdown) {
      HaltTrading("Max drawdown reached: " + DoubleToString(drawdown, 2) + "%");
      return false;
   }

   double dailyLossPct = MathAbs(daily.pnl) / equity * 100.0;
   if(daily.pnl < 0 && dailyLossPct >= MaxDailyLoss) {
      HaltTrading("Daily loss limit reached: " + DoubleToString(dailyLossPct, 2) + "%");
      return false;
   }

   double dailyTarget = GetDailyTarget();
   double dailyGainPct = daily.pnl / equity * 100.0;
   if(daily.pnl > 0 && dailyGainPct >= dailyTarget) {
      HaltTrading("Daily target reached: " + DoubleToString(dailyGainPct, 2) + "%");
      CloseProfitablePositions();
      return false;
   }

   if(daily.trade_count >= MaxDailyTrades) {
      HaltTrading("Max daily trades reached: " + IntegerToString(daily.trade_count));
      return false;
   }

   if(CountOpenPositions() >= MaxOpenTrades) return false;

   return true;
}

//+------------------------------------------------------------------+
//| Get daily target based on profile                                 |
//+------------------------------------------------------------------+
double GetDailyTarget() {
   switch(TargetProfile) {
      case 0: return DailyTargetConservative;
      case 1: return DailyTargetModerate;
      case 2: return DailyTargetAggressive;
      default: return DailyTargetModerate;
   }
}

//+------------------------------------------------------------------+
//| Halt trading                                                      |
//+------------------------------------------------------------------+
void HaltTrading(string reason) {
   if(!daily.halted) {
      daily.halted = true;
      daily.halt_reason = reason;
      Print("TRADING HALTED: ", reason);
   }
}

//+------------------------------------------------------------------+
//| Count open positions                                              |
//+------------------------------------------------------------------+
int CountOpenPositions() {
   int count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0) {
         if(PositionGetString(POSITION_SYMBOL) == _Symbol &&
            PositionGetInteger(POSITION_MAGIC) == MagicNumber) {
            count++;
         }
      }
   }
   return count;
}

//+------------------------------------------------------------------+
//| Check if has open position                                        |
//+------------------------------------------------------------------+
bool HasOpenPosition() {
   return CountOpenPositions() > 0;
}

//+------------------------------------------------------------------+
//| Detect market regime                                              |
//+------------------------------------------------------------------+
ENUM_MARKET_REGIME DetectMarketRegime() {
   double adxVal = GetIndicatorValue(handle_adx, 0);
   double atrVal = GetIndicatorValue(handle_atr, 0);
   double bbUpper = GetIndicatorValue(handle_bb, 1);
   double bbLower = GetIndicatorValue(handle_bb, 2);
   double bbMiddle = GetIndicatorValue(handle_bb, 0);
   double bbWidth = (bbUpper - bbLower) / bbMiddle;
   double volume = (double)SymbolInfoInteger(_Symbol, SYMBOL_VOLUME);

   double atrAvg = CalculateATRAverage(20);
   double bbWidthAvg = CalculateBBWidthAverage(20);
   double volumeAvg = CalculateVolumeAverage(20);
   double spread = SymbolInfoInteger(_Symbol, SYMBOL_SPREAD);
   double spreadAvg = CalculateSpreadAverage(20);

   if(spread > spreadAvg * 3.0 || volume < volumeAvg * 0.5)
      return REGIME_LOW_LIQUIDITY;

   if(atrVal > atrAvg * 1.5 && bbWidth > bbWidthAvg * 2.0)
      return REGIME_VOLATILE;

   if(adxVal > 30) return REGIME_STRONG_TRENDING;
   if(adxVal >= 20 && adxVal <= 30) return REGIME_WEAK_TRENDING;
   if(adxVal < 20 && bbWidth < bbWidthAvg * 0.8) return REGIME_RANGING;

   return REGIME_WEAK_TRENDING;
}

//+------------------------------------------------------------------+
//| Select optimal strategy                                           |
//+------------------------------------------------------------------+
ENUM_STRATEGY_TYPE SelectStrategy(ENUM_MARKET_REGIME regime) {
   switch(regime) {
      case REGIME_STRONG_TRENDING: return STRAT_TREND_FOLLOWING;
      case REGIME_WEAK_TRENDING:   return STRAT_MOMENTUM;
      case REGIME_RANGING:         return STRAT_MEAN_REVERSION;
      case REGIME_VOLATILE:        return STRAT_BREAKOUT;
      case REGIME_NEWS_DRIVEN:     return STRAT_NONE;
      case REGIME_LOW_LIQUIDITY:   return STRAT_SCALPING;
      default:                     return STRAT_MOMENTUM;
   }
}

//+------------------------------------------------------------------+
//| Get ML prediction via REST API                                    |
//+------------------------------------------------------------------+
MlPrediction GetMLPrediction() {
   MlPrediction pred;
   pred.direction = "NEUTRAL";
   pred.confidence = 0;
   pred.regime = "unknown";
   pred.regime_confidence = 0;
   pred.should_trade = false;

   if(!UseMLPrediction) {
      pred.should_trade = true;
      return pred;
   }

   string url = ML_API_URL + _Symbol + "?timeframe=H1";
   string headers = "Content-Type: application/json\r\n";
   char   post[];
   char   result[];
   int    res;

   res = WebRequest("GET", url, headers, ML_API_TIMEOUT, post, result);

   if(res == 200) {
      string response = CharArrayToString(result);
      pred.direction = JsonGetString(response, "direction");
      pred.confidence = JsonGetDouble(response, "confidence") * 100.0;
      pred.regime = JsonGetString(response, "regime");
      pred.regime_confidence = JsonGetDouble(response, "regime_confidence") * 100.0;
      pred.should_trade = (pred.confidence >= MinConfidence);
   } else {
      Print("ML API request failed. Code: ", res);
   }

   return pred;
}

//+------------------------------------------------------------------+
//| Generate trade signal                                             |
//+------------------------------------------------------------------+
TradeSignal GenerateSignal(ENUM_STRATEGY_TYPE strategy, ENUM_MARKET_REGIME regime, MlPrediction mlPred) {
   TradeSignal signal;
   signal.direction = DIR_NONE;
   signal.regime = regime;
   signal.strategy = strategy;
   signal.confidence = mlPred.confidence;

   double rsi = GetIndicatorValue(handle_rsi, 0);
   double macdMain = GetIndicatorValue(handle_macd_main, 0);
   double macdSig = GetIndicatorValue(handle_macd_signal, 1);
   double emaFast = GetIndicatorValue(handle_ema_fast, 0);
   double emaSlow = GetIndicatorValue(handle_ema_slow, 0);
   double atr = GetIndicatorValue(handle_atr, 0);
   double bbUpper = GetIndicatorValue(handle_bb, 1);
   double bbLower = GetIndicatorValue(handle_bb, 2);

   switch(strategy) {
      case STRAT_TREND_FOLLOWING:
         if(mlPred.direction == "BULLISH" && emaFast > emaSlow && macdMain > macdSig) {
            signal.direction = DIR_BUY;
            signal.entry_price = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
            signal.stop_loss = signal.entry_price - atr * 2.0;
            signal.take_profit = signal.entry_price + atr * 3.0;
         } else if(mlPred.direction == "BEARISH" && emaFast < emaSlow && macdMain < macdSig) {
            signal.direction = DIR_SELL;
            signal.entry_price = SymbolInfoDouble(_Symbol, SYMBOL_BID);
            signal.stop_loss = signal.entry_price + atr * 2.0;
            signal.take_profit = signal.entry_price - atr * 3.0;
         }
         break;

      case STRAT_MOMENTUM:
         if(mlPred.direction == "BULLISH" && rsi < 40 && macdMain > macdSig) {
            signal.direction = DIR_BUY;
            signal.entry_price = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
            signal.stop_loss = signal.entry_price - atr * 1.5;
            signal.take_profit = signal.entry_price + atr * 3.0;
         } else if(mlPred.direction == "BEARISH" && rsi > 60 && macdMain < macdSig) {
            signal.direction = DIR_SELL;
            signal.entry_price = SymbolInfoDouble(_Symbol, SYMBOL_BID);
            signal.stop_loss = signal.entry_price + atr * 1.5;
            signal.take_profit = signal.entry_price - atr * 3.0;
         }
         break;

      case STRAT_MEAN_REVERSION:
         if(mlPred.direction == "BULLISH" && rsi < 30) {
            signal.direction = DIR_BUY;
            signal.entry_price = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
            signal.stop_loss = bbLower - atr * 0.5;
            signal.take_profit = bbUpper;
         } else if(mlPred.direction == "BEARISH" && rsi > 70) {
            signal.direction = DIR_SELL;
            signal.entry_price = SymbolInfoDouble(_Symbol, SYMBOL_BID);
            signal.stop_loss = bbUpper + atr * 0.5;
            signal.take_profit = bbLower;
         }
         break;

      case STRAT_BREAKOUT:
         if(mlPred.direction == "BULLISH" && SymbolInfoDouble(_Symbol, SYMBOL_ASK) > bbUpper) {
            signal.direction = DIR_BUY;
            signal.entry_price = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
            signal.stop_loss = signal.entry_price - atr * 2.5;
            signal.take_profit = signal.entry_price + atr * 4.0;
         } else if(mlPred.direction == "BEARISH" && SymbolInfoDouble(_Symbol, SYMBOL_BID) < bbLower) {
            signal.direction = DIR_SELL;
            signal.entry_price = SymbolInfoDouble(_Symbol, SYMBOL_BID);
            signal.stop_loss = signal.entry_price + atr * 2.5;
            signal.take_profit = signal.entry_price - atr * 4.0;
         }
         break;

      case STRAT_SCALPING:
         if(mlPred.direction == "BULLISH" && rsi < 35) {
            signal.direction = DIR_BUY;
            signal.entry_price = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
            signal.stop_loss = signal.entry_price - atr * 0.8;
            signal.take_profit = signal.entry_price + atr * 1.2;
         } else if(mlPred.direction == "BEARISH" && rsi > 65) {
            signal.direction = DIR_SELL;
            signal.entry_price = SymbolInfoDouble(_Symbol, SYMBOL_BID);
            signal.stop_loss = signal.entry_price + atr * 0.8;
            signal.take_profit = signal.entry_price - atr * 1.2;
         }
         break;

      default:
         break;
   }

   signal.volume = CalculatePositionSize(signal);

   return signal;
}

//+------------------------------------------------------------------+
//| Calculate position size                                           |
//+------------------------------------------------------------------+
double CalculatePositionSize(TradeSignal signal) {
   double equity = AccountInfoDouble(ACCOUNT_EQUITY);
   double riskPct = MaxRiskPerTrade;

   switch(regime) {
      case REGIME_STRONG_TRENDING: riskPct *= 1.0; break;
      case REGIME_WEAK_TRENDING:   riskPct *= 0.8; break;
      case REGIME_RANGING:         riskPct *= 0.7; break;
      case REGIME_VOLATILE:        riskPct *= 0.5; break;
      case REGIME_NEWS_DRIVEN:     riskPct = 0; break;
      case REGIME_LOW_LIQUIDITY:   riskPct *= 0.3; break;
   }

   double riskAmount = equity * riskPct / 100.0;
   double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   double slDistance = MathAbs(signal.entry_price - signal.stop_loss);

   if(tickSize == 0 || tickValue == 0) return SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);

   double positionSize = riskAmount / (slDistance / tickSize * tickValue);

   double minLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maxLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   double lotStep = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);

   positionSize = MathFloor(positionSize / lotStep) * lotStep;
   positionSize = MathMax(minLot, MathMin(maxLot, positionSize));

   return NormalizeDouble(positionSize, 2);
}

//+------------------------------------------------------------------+
//| Validate signal                                                   |
//+------------------------------------------------------------------+
bool ValidateSignal(TradeSignal signal) {
   if(signal.direction == DIR_NONE) return false;
   if(signal.volume <= 0) return false;
   if(signal.stop_loss == 0) return false;
   if(signal.take_profit == 0) return false;

   double slPips = MathAbs(signal.entry_price - signal.stop_loss) / SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   double tpPips = MathAbs(signal.take_profit - signal.entry_price) / SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   double rrRatio = tpPips / slPips;

   if(rrRatio < 1.5) {
      Print("Risk:Reward too low: ", DoubleToString(rrRatio, 2));
      return false;
   }

   return true;
}

//+------------------------------------------------------------------+
//| Execute trade                                                     |
//+------------------------------------------------------------------+
void ExecuteTrade(TradeSignal signal) {
   if(signal.direction == DIR_NONE) return;

   bool result = false;

   if(signal.direction == DIR_BUY) {
      result = trade.Buy(signal.volume, _Symbol, signal.entry_price,
                         signal.stop_loss, signal.take_profit,
                         "DTA_" + EnumToString(signal.strategy));
   } else if(signal.direction == DIR_SELL) {
      result = trade.Sell(signal.volume, _Symbol, signal.entry_price,
                          signal.stop_loss, signal.take_profit,
                          "DTA_" + EnumToString(signal.strategy));
   }

   if(result) {
      daily.trade_count++;
      Print("Trade executed: ", EnumToString(signal.direction),
            " Lot: ", DoubleToString(signal.volume, 2),
            " Regime: ", EnumToString(signal.regime),
            " Strategy: ", EnumToString(signal.strategy));
   } else {
      Print("Trade execution failed. Error: ", GetLastError());
   }
}

//+------------------------------------------------------------------+
//| Manage existing positions                                         |
//+------------------------------------------------------------------+
void ManageExistingPositions() {
   double atr = GetIndicatorValue(handle_atr, 0);
   double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);

   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;

      double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
      double currentPrice = PositionGetDouble(POSITION_PRICE_CURRENT);
      double sl = PositionGetDouble(POSITION_SL);
      double tp = PositionGetDouble(POSITION_TP);
      double volume = PositionGetDouble(POSITION_VOLUME);
      long posType = PositionGetInteger(POSITION_TYPE);

      double riskPips = MathAbs(openPrice - sl) / point;
      double currentPips;
      if(posType == POSITION_TYPE_BUY)
         currentPips = (currentPrice - openPrice) / point;
      else
         currentPips = (openPrice - currentPrice) / point;

      // Breakeven at 1R
      if(currentPips >= riskPips * 1.0) {
         MoveToBreakeven(ticket, openPrice, sl, tp, posType);
      }

      // Trail stop at 2R
      if(currentPips >= riskPips * 2.0) {
         TrailStop(ticket, currentPips, riskPips, atr, posType);
      }

      // Partial close at 3R (50%)
      if(currentPips >= riskPips * 3.0 && volume > SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN) * 1.5) {
         PartialClose(ticket, volume * 0.5);
      }
   }
}

//+------------------------------------------------------------------+
//| Move stop loss to breakeven                                       |
//+------------------------------------------------------------------+
void MoveToBreakeven(ulong ticket, double openPrice, double currentSL, double currentTP, long posType) {
   double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   double newSL;

   if(posType == POSITION_TYPE_BUY) {
      newSL = openPrice + point * 10;
      if(currentSL >= newSL) return;
   } else {
      newSL = openPrice - point * 10;
      if(currentSL > 0 && currentSL <= newSL) return;
   }

   trade.PositionModify(ticket, newSL, currentTP);
}

//+------------------------------------------------------------------+
//| Trail stop loss                                                   |
//+------------------------------------------------------------------+
void TrailStop(ulong ticket, double currentPips, double riskPips, double atr, long posType) {
   double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   double trailDistance = atr * 1.5;
   double newSL;

   if(posType == POSITION_TYPE_BUY) {
      newSL = SymbolInfoDouble(_Symbol, SYMBOL_BID) - trailDistance;
      if(newSL > PositionGetDouble(POSITION_SL) && newSL > PositionGetDouble(POSITION_PRICE_OPEN)) {
         trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP));
      }
   } else {
      newSL = SymbolInfoDouble(_Symbol, SYMBOL_ASK) + trailDistance;
      if(newSL < PositionGetDouble(POSITION_SL) || PositionGetDouble(POSITION_SL) == 0) {
         if(newSL < PositionGetDouble(POSITION_PRICE_OPEN)) {
            trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP));
         }
      }
   }
}

//+------------------------------------------------------------------+
//| Partial close position                                            |
//+------------------------------------------------------------------+
void PartialClose(ulong ticket, double closeVolume) {
   double minLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double lotStep = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);

   closeVolume = MathFloor(closeVolume / lotStep) * lotStep;
   closeVolume = MathMax(minLot, closeVolume);

   if(closeVolume >= minLot) {
      trade.PositionClosePartial(ticket, closeVolume);
      Print("Partial close: ", DoubleToString(closeVolume, 2), " lots on ticket ", ticket);
   }
}

//+------------------------------------------------------------------+
//| Close profitable positions                                        |
//+------------------------------------------------------------------+
void CloseProfitablePositions() {
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;

      double profit = PositionGetDouble(POSITION_PROFIT);
      if(profit > 0) {
         trade.PositionClose(ticket);
         Print("Closed profitable position: ticket=", ticket, " profit=", profit);
      }
   }
}

//+------------------------------------------------------------------+
//| Get indicator value                                               |
//+------------------------------------------------------------------+
double GetIndicatorValue(int handle, int buffer, int shift = 0) {
   double value[];
   ArraySetAsSeries(value, true);
   if(CopyBuffer(handle, buffer, shift, 1, value) > 0)
      return value[0];
   return 0;
}

//+------------------------------------------------------------------+
//| Calculate ATR average                                             |
//+------------------------------------------------------------------+
double CalculateATRAverage(int period) {
   double atrArr[];
   ArraySetAsSeries(atrArr, true);
   if(CopyBuffer(handle_atr, 0, 1, period, atrArr) < period) return 0;
   double sum = 0;
   for(int i = 0; i < period; i++) sum += atrArr[i];
   return sum / period;
}

//+------------------------------------------------------------------+
//| Calculate BB width average                                        |
//+------------------------------------------------------------------+
double CalculateBBWidthAverage(int period) {
   double widths[];
   ArraySetAsSeries(widths, true);

   double upper[], middle[], lower[];
   ArraySetAsSeries(upper, true);
   ArraySetAsSeries(middle, true);
   ArraySetAsSeries(lower, true);

   if(CopyBuffer(handle_bb, 1, 1, period, upper) < period) return 0;
   if(CopyBuffer(handle_bb, 0, 1, period, middle) < period) return 0;
   if(CopyBuffer(handle_bb, 2, 1, period, lower) < period) return 0;

   double sum = 0;
   for(int i = 0; i < period; i++) {
      if(middle[i] > 0)
         sum += (upper[i] - lower[i]) / middle[i];
   }
   return sum / period;
}

//+------------------------------------------------------------------+
//| Calculate volume average                                          |
//+------------------------------------------------------------------+
double CalculateVolumeAverage(int period) {
   double sum = 0;
   for(int i = 1; i <= period; i++) {
      sum += (double)iVolume(_Symbol, PERIOD_CURRENT, i);
   }
   return sum / period;
}

//+------------------------------------------------------------------+
//| Calculate spread average                                          |
//+------------------------------------------------------------------+
double CalculateSpreadAverage(int period) {
   double sum = 0;
   for(int i = 1; i <= period; i++) {
      sum += (double)iSpread(_Symbol, PERIOD_CURRENT, i);
   }
   return sum / period;
}

//+------------------------------------------------------------------+
//| JSON helper functions                                             |
//+------------------------------------------------------------------+
string JsonGetString(string json, string key) {
   string search = "\"" + key + "\":\"";
   int pos = StringFind(json, search);
   if(pos < 0) return "";
   pos += StringLen(search);
   int end = StringFind(json, "\"", pos);
   if(end < 0) return "";
   return StringSubstr(json, pos, end - pos);
}

double JsonGetDouble(string json, string key) {
   string search = "\"" + key + "\":";
   int pos = StringFind(json, search);
   if(pos < 0) return 0;
   pos += StringLen(search);
   string val = "";
   for(int i = pos; i < StringLen(json); i++) {
      ushort ch = StringGetCharacter(json, i);
      if((ch >= '0' && ch <= '9') || ch == '.' || ch == '-')
         val += ShortToString(ch);
      else
         break;
   }
   return StringToDouble(val);
}
//+------------------------------------------------------------------+
