"""
MQL5 Expert Advisor code generator.
Generates compilable .mq5 source code from EA parameters.
"""

import logging
from typing import Any, Dict

logger = logging.getLogger("eas.mql5_generator")


class MQL5Generator:
    """Generates MQL5 Expert Advisor source code."""

    def generate_ea(
        self,
        name: str,
        symbol: str,
        timeframe: str,
        strategy_type: str,
        parameters: Dict[str, Any],
        risk_per_trade: float = 2.0,
        use_stop_loss: bool = True,
        use_take_profit: bool = True,
        use_trailing_stop: bool = False,
        trailing_stop_pips: int = 0,
    ) -> str:
        sl_pips = parameters.get("sl_pips", 50)
        tp_pips = parameters.get("tp_pips", 100)
        magic = parameters.get("magic_number", 123456)
        lot_size = parameters.get("lot_size", 0.01)

        code = f'''//+------------------------------------------------------------------+
//| {name}.mq5
//| Generated by Dutchkem Trading AI
//| Strategy: {strategy_type}
//| Symbol: {symbol} | Timeframe: {timeframe}
//+------------------------------------------------------------------+
#property copyright "Dutchkem Trading AI"
#property link      "https://www.dutchkem.com"
#property version   "1.00"
#property strict

#include <Trade\\Trade.mqh>

input double InpLotSize       = {lot_size};       // Lot Size
input int    InpMagicNumber   = {magic};     // Magic Number
input int    InpStopLoss      = {sl_pips};      // Stop Loss (pips)
input int    InpTakeProfit    = {tp_pips};     // Take Profit (pips)
input bool   InpUseTrailing   = {"true" if use_trailing_stop else "false"};   // Use Trailing Stop
input int    InpTrailingPips  = {trailing_stop_pips};  // Trailing Stop (pips)

CTrade trade;

int OnInit()
{{
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(10);
   trade.SetTypeFilling(ORDER_FILLING_IOC);
   return(INIT_SUCCEEDED);
}}

void OnDeinit(const int reason)
{{
}}

void OnTick()
{{
   if(!IsNewBar()) return;

   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   int digits = (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS);
   double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   double pipValue = (digits == 3 || digits == 5) ? point * 10 : point;

   if(InpUseTrailing)
      ManageTrailingStop(pipValue);

   int signal = GetSignal();
   if(signal == 0) return;

   if(PositionsTotal() > 0)
      ClosePositions();

   if(signal == 1)
   {{
      double sl = use_stop_loss ? NormalizeDouble(ask - InpStopLoss * pipValue, digits) : 0;
      double tp = use_take_profit ? NormalizeDouble(ask + InpTakeProfit * pipValue, digits) : 0;
      trade.Buy(InpLotSize, _Symbol, ask, sl, tp, name);
   }}
   else if(signal == -1)
   {{
      double sl = use_stop_loss ? NormalizeDouble(bid + InpStopLoss * pipValue, digits) : 0;
      double tp = use_take_profit ? NormalizeDouble(bid - InpTakeProfit * pipValue, digits) : 0;
      trade.Sell(InpLotSize, _Symbol, bid, sl, tp, name);
   }}
}}

int GetSignal()
{{
   // Strategy: {strategy_type}
   // TODO: Implement {strategy_type} signal logic
   return 0;
}}

bool IsNewBar()
{{
   static datetime lastBar = 0;
   datetime currentBar = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(lastBar != currentBar)
   {{
      lastBar = currentBar;
      return true;
   }}
   return false;
}}

void ClosePositions()
{{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {{
      ulong ticket = PositionGetTicket(i);
      if(PositionSelectByTicket(ticket))
      {{
         if(PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
            trade.PositionClose(ticket);
      }}
   }}
}}

void ManageTrailingStop(double pipValue)
{{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {{
      ulong ticket = PositionGetTicket(i);
      if(!PositionSelectByTicket(ticket)) continue;
      if(PositionGetInteger(POSITION_MAGIC) != InpMagicNumber) continue;

      double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
      double currentSL = PositionGetDouble(POSITION_SL);
      double currentTP = PositionGetDouble(POSITION_TP);
      long posType = PositionGetInteger(POSITION_TYPE);
      int digits = (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS);

      if(posType == POSITION_TYPE_BUY)
      {{
         double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
         double newSL = NormalizeDouble(bid - InpTrailingPips * pipValue, digits);
         if(newSL > currentSL + pipValue && bid - newSL > pipValue)
            trade.PositionModify(ticket, newSL, currentTP);
      }}
      else if(posType == POSITION_TYPE_SELL)
      {{
         double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
         double newSL = NormalizeDouble(ask + InpTrailingPips * pipValue, digits);
         if(newSL < currentSL - pipValue || currentSL == 0)
         {{
            if(newSL - ask > pipValue)
               trade.PositionModify(ticket, newSL, currentTP);
         }}
      }}
   }}
}}
'''
        logger.info("Generated MQL5 EA: %s (%s %s)", name, symbol, timeframe)
        return code


mql5_generator = MQL5Generator()
