# Generated by Django 4.2.30 on 2026-08-28 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedTradeSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('TODAY', 'Today'), ('WEEK', 'This Week'), ('MONTH', 'This Month'), ('ALL_TIME', 'All Time')], max_length=20)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('average_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('best_trade', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('worst_trade', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('profit_factor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cached_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_trade_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cached_at'],
                'unique_together': {('user', 'period')},
            },
        ),
        migrations.CreateModel(
            name='CachedSymbolBreakdown',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol_name', models.CharField(max_length=20)),
                ('total_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('period', models.CharField(default='ALL_TIME', max_length=20)),
                ('cached_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_symbol_breakdowns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_pnl'],
                'unique_together': {('user', 'symbol_name', 'period')},
            },
        ),
        migrations.CreateModel(
            name='CachedDailyPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('daily_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('daily_pnl_percent', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cached_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_daily_performances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
