apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dutchkem

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: fortress-api
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Namespace
      name: dutchkem
    patch: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: dutchkem
        labels:
          region: europe
          compliance: gdpr

configMapGenerator:
  - name: fortress-config
    literals:
      - REGION=europe
      - COMPLIANCE_REGIME=gdpr
      - DEFAULT_CURRENCY=EUR
      - CLUSTER=aws-frankfurt
