# Generated by Django 4.2.30 on 2026-08-27 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indicators', '0001_initial'),
        ('trading', '0001_initial'),
        ('expert_advisors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertadvisor',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_advisors', to='trading.symbol'),
        ),
        migrations.AddField(
            model_name='expertadvisor',
            name='timeframe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_advisors', to='indicators.timeframe'),
        ),
        migrations.AddField(
            model_name='expertadvisor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_advisors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eadeployment',
            name='ea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='expert_advisors.expertadvisor'),
        ),
        migrations.AddField(
            model_name='eabacktestresult',
            name='ea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_results_detail', to='expert_advisors.expertadvisor'),
        ),
    ]
