# Generated by Django 4.2.20 on 2026-09-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='security_se_event_t_1a00f0_idx',
            old_name='security_ev_event__b0d5c7_idx',
        ),
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='security_se_ip_addr_7e6b32_idx',
            old_name='security_ev_ip_addr_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='security_se_user_id_6ceb62_idx',
            old_name='security_ev_user_id_c4d5e6_idx',
        ),
        migrations.AlterField(
            model_name='blockedip',
            name='threat_level',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'Info'), (3, 'Medium'), (4, 'High'), (5, 'Critical')], default=4),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='threat_level',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'Info'), (3, 'Medium'), (4, 'High'), (5, 'Critical')], default=0),
        ),
    ]
