# Generated by Django 4.2.30 on 2026-08-27 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrelationMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol_pair', models.CharField(max_length=20)),
                ('correlation', models.DecimalField(decimal_places=4, max_digits=5)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('starting_equity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ending_equity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('daily_pnl', models.DecimalField(decimal_places=2, max_digits=20)),
                ('daily_pnl_percent', models.DecimalField(decimal_places=4, max_digits=5)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_loss', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('avg_win', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('avg_loss', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('risk_reward_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('timeframe_performance', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DrawdownMonitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('peak_equity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('current_equity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('starting_equity_today', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('drawdown_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('daily_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('daily_pnl_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('daily_loss_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('daily_trades_count', models.IntegerField(default=0)),
                ('is_daily_loss_triggered', models.BooleanField(default=False)),
                ('is_drawdown_triggered', models.BooleanField(default=False)),
                ('is_daily_target_triggered', models.BooleanField(default=False)),
                ('is_max_trades_triggered', models.BooleanField(default=False)),
                ('is_circuit_breaker_triggered', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('daily_reset_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PositionSizing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_per_trade', models.DecimalField(decimal_places=2, default=1.0, help_text='Risk per trade as percentage (default: 1%)', max_digits=5)),
                ('account_equity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('risk_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('stop_loss_pips', models.IntegerField()),
                ('position_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('daily_trades_count', models.IntegerField(default=0)),
                ('remaining_daily_budget', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('max_daily_loss', models.DecimalField(decimal_places=2, default=2.0, help_text='Maximum daily loss as percentage (default: 2%)', max_digits=5)),
                ('daily_growth_target', models.DecimalField(decimal_places=4, default=0.14, help_text='Daily growth target as percentage (default: 0.14%)', max_digits=5)),
                ('daily_target_lock', models.DecimalField(decimal_places=2, default=0.4, help_text='Daily target lock - trading stops after this gain (default: 0.4%)', max_digits=5)),
                ('max_daily_trades', models.IntegerField(default=10, help_text='Maximum number of trades per day (default: 10)')),
                ('max_position_size', models.DecimalField(decimal_places=2, default=1.0, help_text='Maximum position size as percentage per trade (default: 1%)', max_digits=5)),
                ('max_open_positions', models.IntegerField(default=5, help_text='Maximum open positions per instrument (default: 5)')),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=15.0, help_text='Maximum drawdown as percentage (default: 15%)', max_digits=5)),
                ('max_correlation', models.DecimalField(decimal_places=2, default=0.7, help_text='Maximum correlation between positions (default: 0.70)', max_digits=5)),
                ('min_risk_reward_ratio', models.DecimalField(decimal_places=2, default=2.0, help_text='Minimum risk-reward ratio (default: 1:2)', max_digits=5)),
                ('target_daily_growth', models.DecimalField(decimal_places=4, default=0.14, help_text='Target daily growth percentage (default: 0.14%)', max_digits=5)),
                ('target_monthly_growth', models.DecimalField(decimal_places=2, default=4.2, help_text='Target monthly growth percentage (default: 4.2%)', max_digits=5)),
                ('target_annual_growth', models.DecimalField(decimal_places=2, default=50.0, help_text='Target annual growth percentage (default: 50%+)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'risk parameters',
            },
        ),
        migrations.CreateModel(
            name='RiskAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('DRAWDOWN', 'Drawdown Alert'), ('DAILY_LOSS', 'Daily Loss Alert'), ('DAILY_TARGET', 'Daily Target Alert'), ('POSITION_SIZE', 'Position Size Alert'), ('CORRELATION', 'Correlation Alert'), ('CIRCUIT_BREAKER', 'Circuit Breaker Triggered'), ('MAX_DAILY_TRADES', 'Max Daily Trades Reached'), ('DAILY_TARGET_LOCK', 'Daily Target Lock Triggered'), ('MARGIN_CALL', 'Margin Call')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('message', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
