# Generated by Django 4.2.30 on 2026-08-27 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0001_initial'),
        ('indicators', '0002_initial'),
        ('risk_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionsizing',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.symbol'),
        ),
        migrations.AddField(
            model_name='positionsizing',
            name='timeframe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_sizings', to='indicators.timeframe'),
        ),
        migrations.AddField(
            model_name='positionsizing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_sizings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drawdownmonitor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawdown_monitors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyperformance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_performances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='correlationmatrix',
            name='timeframe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.timeframe'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyperformance',
            unique_together={('user', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='correlationmatrix',
            unique_together={('symbol_pair', 'timeframe')},
        ),
    ]
