# Generated by Django 4.2.30 on 2026-08-29 09:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldEdgeRiskParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Gold Edge Risk', max_length=100)),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=30.0, help_text='Maximum drawdown as percentage — Gold Edge allows 20-40% (default: 30%)', max_digits=5)),
                ('max_drawdown_warning', models.DecimalField(decimal_places=2, default=20.0, help_text='Drawdown warning threshold — reduce position size (default: 20%)', max_digits=5)),
                ('atr_position_sizing', models.BooleanField(default=True, help_text='Use ATR-based position sizing instead of fixed percentage')),
                ('atr_risk_multiplier', models.DecimalField(decimal_places=2, default=2.0, help_text='ATR multiplier for stop loss distance (default: 2.0)', max_digits=5)),
                ('max_risk_per_trade_pct', models.DecimalField(decimal_places=2, default=2.0, help_text='Maximum risk per trade as percentage (default: 2%)', max_digits=5)),
                ('min_risk_per_trade_pct', models.DecimalField(decimal_places=2, default=0.5, help_text='Minimum risk per trade as percentage (default: 0.5%)', max_digits=5)),
                ('max_consecutive_losses', models.IntegerField(default=5, help_text='Max consecutive losses before circuit breaker (default: 5)')),
                ('cooldown_minutes_after_circuit_breaker', models.IntegerField(default=60, help_text='Cooldown period in minutes after circuit breaker triggers (default: 60)')),
                ('max_daily_gold_edge_trades', models.IntegerField(default=8, help_text='Maximum Gold Edge trades per day (default: 8)')),
                ('min_time_between_trades_minutes', models.IntegerField(default=15, help_text='Minimum time between Gold Edge trades in minutes (default: 15)')),
                ('min_matrix_score_to_trade', models.DecimalField(decimal_places=2, default=0.6, help_text='Minimum Gold Edge matrix score to allow trade (default: 0.60)', max_digits=4)),
                ('min_risk_reward_ratio', models.DecimalField(decimal_places=2, default=1.5, help_text='Minimum risk-reward ratio for Gold Edge trades (default: 1.5)', max_digits=5)),
                ('max_gold_exposure_pct', models.DecimalField(decimal_places=2, default=50.0, help_text='Maximum total gold exposure as % of equity (default: 50%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'gold edge risk parameters',
            },
        ),
        migrations.AddField(
            model_name='riskparameter',
            name='gold_edge_atr_position_sizing',
            field=models.BooleanField(default=True, help_text='Use ATR-based position sizing for Gold Edge trades'),
        ),
        migrations.AddField(
            model_name='riskparameter',
            name='gold_edge_atr_risk_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='ATR-based position size multiplier (default: 1.5x for gold volatility)', max_digits=5),
        ),
        migrations.AddField(
            model_name='riskparameter',
            name='gold_edge_circuit_breaker_consecutive_losses',
            field=models.IntegerField(default=4, help_text='Consecutive losing trades to trigger Gold Edge circuit breaker (default: 4)'),
        ),
        migrations.AddField(
            model_name='riskparameter',
            name='gold_edge_circuit_breaker_loss',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Gold Edge daily loss circuit breaker (default: 5%, higher than standard 2%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='riskparameter',
            name='gold_edge_enabled',
            field=models.BooleanField(default=False, help_text='Enable Gold Edge specific risk overrides'),
        ),
        migrations.AddField(
            model_name='riskparameter',
            name='gold_edge_max_drawdown',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Gold Edge max drawdown tolerance as percentage (default: 30%, range 20-40%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='riskparameter',
            name='gold_edge_min_risk_reward',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Gold Edge minimum risk-reward ratio (default: 1.5, lower than standard 2.0)', max_digits=5),
        ),
    ]
