# Generated by Django 4.2.30 on 2026-08-30 21:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0004_drawdownmonitor_gold_edge_consecutive_losses'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default Trading Settings', max_length=100)),
                ('trading_mode', models.CharField(choices=[('auto', 'Full Auto — Execute trades automatically'), ('semi', 'Semi-Auto — Signals require approval'), ('manual', 'Manual — Signals logged only')], default='semi', help_text='auto = full auto-trading, semi = requires approval, manual = log only', max_length=10)),
                ('max_slippage_pips', models.DecimalField(decimal_places=2, default=0.5, help_text='Maximum allowed slippage in pips before rejecting a trade', max_digits=5)),
                ('max_spread_pips', models.DecimalField(decimal_places=2, default=0.5, help_text='Maximum allowed spread in pips before rejecting a trade', max_digits=5)),
                ('min_confidence', models.DecimalField(decimal_places=2, default=0.65, help_text='Minimum signal confidence to consider executing (0.0-1.0)', max_digits=5)),
                ('active_symbols', models.TextField(default='XAUUSD,EURUSD,GBPUSD,USDJPY,AUDUSD,USDCAD,NZDUSD,USDCHF,EURGBP,EURJPY', help_text='Comma-separated list of symbols to trade')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trading Settings',
                'verbose_name_plural': 'Trading Settings',
            },
        ),
    ]
