# Generated by Django 4.2.30 on 2026-09-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0005_trading_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingsettings',
            name='active_symbols',
            field=models.TextField(
                default='EURUSD,GBPUSD,USDJPY,USDCHF,AUDUSD,USDCAD,NZDUSD,EURGBP,EURJPY,GBPJPY,AUDJPY,EURAUD,EURCHF,GBPCAD,USDTRY,USDZAR,USDMXN,USDCNH,XAUUSD,XAGUSD,XAUEUR,BTCUSD,ETHUSD,SOLUSD,US30,US500,NAS100,GER40',
                help_text='Comma-separated list of symbols to trade',
            ),
        ),
    ]
