# Generated by Django 6.0.8 on 2026-09-02 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0006_alter_tradingsettings_active_symbols'),
        ('risk_management', '0007_add_v65_profit_target_fields'),
    ]

    operations = [
    ]
