# Generated by Django 4.2.30 on 2026-08-27 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('PAYSTACK', 'Paystack'), ('FLUTTERWAVE', 'Flutterwave'), ('STRIPE', 'Stripe'), ('COINBASE', 'Coinbase'), ('PAYPAL', 'PayPal'), ('SKRILL', 'Skrill'), ('NETELLER', 'Neteller'), ('MPESA', 'M-Pesa'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=50)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('supports_deposits', models.BooleanField(default=True)),
                ('supports_withdrawals', models.BooleanField(default=True)),
                ('min_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('max_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('min_withdrawal', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('max_withdrawal', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('deposit_fee_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('withdrawal_fee_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('deposit_processing_time', models.CharField(default='Instant', max_length=50)),
                ('withdrawal_processing_time', models.CharField(default='1-3 Business Days', max_length=50)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('api_secret', models.CharField(blank=True, max_length=255)),
                ('webhook_secret', models.CharField(blank=True, max_length=255)),
                ('config', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name_plural': 'payment gateways',
            },
        ),
        migrations.CreateModel(
            name='UserPaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method_type', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=100)),
                ('last_four', models.CharField(blank=True, max_length=4)),
                ('is_default', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('details_encrypted', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentgateway')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('BASIC', 'Basic'), ('ADVANCED', 'Advanced'), ('FULL', 'Full')], max_length=20)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='NOT_STARTED', max_length=20)),
                ('document_type', models.CharField(blank=True, max_length=50)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('document_front', models.ImageField(blank=True, null=True, upload_to='kyc/front/')),
                ('document_back', models.ImageField(blank=True, null=True, upload_to='kyc/back/')),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='kyc/selfie/')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRADING_PROFIT', 'Trading Profit'), ('TRADING_LOSS', 'Trading Loss'), ('COMMISSION', 'Commission'), ('SWAP', 'Swap'), ('BONUS', 'Bonus'), ('REFUND', 'Refund')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('gateway_reference', models.CharField(blank=True, max_length=255)),
                ('gateway_response', models.JSONField(default=dict)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentgateway')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'transaction_type', '-created_at'], name='payments_tr_user_id_32faa5_idx'), models.Index(fields=['status'], name='payments_tr_status_96e6c0_idx')],
            },
        ),
    ]
