# Generated by Django 4.2.30 on 2026-08-29 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_action_2a1328_idx',
            old_name='audit_audit_action_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_user_id_e8be02_idx',
            old_name='audit_audit_user_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_resourc_2a3aef_idx',
            old_name='audit_audit_res_idx',
        ),
    ]
