# Generated by Django 4.2.30 on 2026-08-27 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indicators', '0001_initial'),
        ('signals', '0001_initial'),
        ('expert_advisors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('MAJOR', 'Major'), ('MINOR', 'Minor'), ('EXOTIC', 'Exotic'), ('COMMODITY', 'Commodity'), ('CRYPTO', 'Crypto'), ('INDEX', 'Index')], max_length=20)),
                ('base_currency', models.CharField(max_length=3)),
                ('quote_currency', models.CharField(max_length=3)),
                ('pip_size', models.DecimalField(decimal_places=6, default=0.0001, max_digits=10)),
                ('spread', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('contract_size', models.DecimalField(decimal_places=2, default=100000, max_digits=10)),
                ('margin_requirement', models.DecimalField(decimal_places=2, default=0.01, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supported_timeframes', models.ManyToManyField(blank=True, to='indicators.timeframe')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('open_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('close_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('swap', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mt5_ticket', models.CharField(blank=True, max_length=50, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expert_advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expert_advisors.expertadvisor')),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='signals.signal')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='trading.symbol')),
                ('timeframe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='indicators.timeframe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('open_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('current_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('margin_used', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='trading.symbol')),
                ('timeframe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='indicators.timeframe')),
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='trading.trade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_type', models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit'), ('STOP', 'Stop'), ('STOP_LIMIT', 'Stop Limit')], max_length=20)),
                ('position_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FILLED', 'Filled'), ('PARTIALLY_FILLED', 'Partially Filled'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('risk_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('risk_reward_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mt5_ticket', models.CharField(blank=True, max_length=50, null=True)),
                ('expiration', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='signals.signal')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='trading.symbol')),
                ('timeframe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='indicators.timeframe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user', 'status'], name='trading_tra_user_id_d8b231_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['symbol', 'status'], name='trading_tra_symbol__744971_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['opened_at'], name='trading_tra_opened__d66fc1_idx'),
        ),
    ]
