# Generated by Django 4.2.30 on 2026-08-27 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicators', '0001_initial'),
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorvalue',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_values', to='trading.symbol'),
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='timeframe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_values', to='indicators.timeframe'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='indicators.indicatorcategory'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='suitable_timeframes',
            field=models.ManyToManyField(related_name='suitable_indicators', to='indicators.timeframe'),
        ),
        migrations.AlterUniqueTogether(
            name='timeframeindicatorconfig',
            unique_together={('timeframe', 'indicator')},
        ),
        migrations.AddIndex(
            model_name='indicatorvalue',
            index=models.Index(fields=['symbol', 'indicator', 'timeframe', '-timestamp'], name='indicators__symbol__027961_idx'),
        ),
    ]
