# Generated by Django 4.2.30 on 2026-08-27 09:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MCPServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('SYNX-MT5', 'SYNX-MT5-MCP'), ('AKTOOLS', 'AkTools Pro'), ('OPENALGO', 'OpenAlgo'), ('CROSSTRADE', 'CrossTrade'), ('OPENTRADING', 'OpenTrading')], max_length=50)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('endpoint_url', models.URLField()),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('api_secret', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('tools_count', models.IntegerField(default=0)),
                ('config', models.JSONField(default=dict)),
                ('health_check_url', models.URLField(blank=True)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('is_healthy', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'MCP servers',
            },
        ),
        migrations.CreateModel(
            name='MCPConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('ERROR', 'Error')], max_length=20)),
                ('requests_count', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('avg_response_time', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='mcp_integration.mcpserver')),
            ],
            options={
                'ordering': ['-connected_at'],
            },
        ),
        migrations.CreateModel(
            name='MCPTool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('parameters_schema', models.JSONField(default=dict)),
                ('return_schema', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='mcp_integration.mcpserver')),
            ],
            options={
                'ordering': ['server', 'name'],
                'unique_together': {('server', 'name')},
            },
        ),
    ]
