# Generated by Django 4.2.30 on 2026-08-27 09:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=3)),
                ('impact_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('VERY_HIGH', 'Very High')], max_length=20)),
                ('scheduled_time', models.DateTimeField()),
                ('actual_value', models.CharField(blank=True, max_length=50)),
                ('forecast_value', models.CharField(blank=True, max_length=50)),
                ('previous_value', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='LivePrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bid', models.DecimalField(decimal_places=6, max_digits=20)),
                ('ask', models.DecimalField(decimal_places=6, max_digits=20)),
                ('spread', models.DecimalField(decimal_places=2, max_digits=5)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'live prices',
            },
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=6, max_digits=20)),
                ('high', models.DecimalField(decimal_places=6, max_digits=20)),
                ('low', models.DecimalField(decimal_places=6, max_digits=20)),
                ('close', models.DecimalField(decimal_places=6, max_digits=20)),
                ('volume', models.BigIntegerField(default=0)),
                ('tick_volume', models.BigIntegerField(default=0)),
                ('spread', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MarketSentiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sentiment_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fear_greed_index', models.DecimalField(decimal_places=2, max_digits=5)),
                ('news_sentiment', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('social_sentiment', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('institutional_flow', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('data_sources', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
