import uuid

from django.conf import settings
from django.db import models


class GoldEdgeConfig(models.Model):
    """
    Configuration for a Gold Edge strategy instance.

    Each user (or the system) can have multiple configs for different
    symbols and risk profiles.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="gold_edge_configs",
        null=True,
        blank=True,
    )
    name = models.CharField(max_length=100, default="Default Gold Edge")
    symbol = models.ForeignKey(
        "trading.Symbol",
        on_delete=models.CASCADE,
        related_name="gold_edge_configs",
    )
    timeframe = models.ForeignKey(
        "indicators.Timeframe",
        on_delete=models.CASCADE,
        related_name="gold_edge_configs",
    )

    # GEC component weights (must sum to 1.0)
    momentum_weight = models.DecimalField(max_digits=4, decimal_places=2, default=0.30)
    trend_weight = models.DecimalField(max_digits=4, decimal_places=2, default=0.30)
    volatility_weight = models.DecimalField(max_digits=4, decimal_places=2, default=0.20)
    dxy_correlation_weight = models.DecimalField(max_digits=4, decimal_places=2, default=0.20)

    # ATR border settings
    atr_period = models.IntegerField(default=14)
    ema_period = models.IntegerField(default=21)
    atr_multipliers = models.JSONField(
        default=list,
        help_text="ATR multiplier layers, e.g. [0.5, 1.0, 1.5, 2.0]",
    )

    # ATR filter settings
    atr_ratio_min = models.DecimalField(max_digits=4, decimal_places=2, default=0.15)
    atr_ratio_max = models.DecimalField(max_digits=4, decimal_places=2, default=1.0)

    # Entry matrix thresholds
    min_gec_score = models.DecimalField(
        max_digits=4, decimal_places=2, default=0.50,
        help_text="Minimum GEC composite score to consider entry (-1 to +1)",
    )
    min_combined_score = models.DecimalField(
        max_digits=4, decimal_places=2, default=0.60,
        help_text="Minimum combined matrix score for high-probability entry",
    )

    # Risk parameters
    risk_per_trade = models.DecimalField(max_digits=5, decimal_places=2, default=1.0)
    sl_atr_multiplier = models.DecimalField(max_digits=4, decimal_places=2, default=2.0)
    tp_atr_multiplier = models.DecimalField(max_digits=4, decimal_places=2, default=3.0)

    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]
        unique_together = ["symbol", "timeframe"]

    def __str__(self):
        return f"GoldEdge: {self.symbol.name} {self.timeframe.code} ({self.name})"


class GoldEdgeSignal(models.Model):
    """
    Signal generated by the Gold Edge composite engine.
    """

    DIRECTION_CHOICES = [
        ("LONG", "Long"),
        ("SHORT", "Short"),
        ("NEUTRAL", "Neutral"),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    config = models.ForeignKey(
        GoldEdgeConfig,
        on_delete=models.CASCADE,
        related_name="signals",
    )
    symbol = models.ForeignKey(
        "trading.Symbol",
        on_delete=models.CASCADE,
        related_name="gold_edge_signals",
    )
    timeframe = models.ForeignKey(
        "indicators.Timeframe",
        on_delete=models.CASCADE,
        related_name="gold_edge_signals",
    )

    direction = models.CharField(max_length=10, choices=DIRECTION_CHOICES, default="NEUTRAL")
    gec_score = models.DecimalField(
        max_digits=5, decimal_places=4, default=0,
        help_text="Gold Edge Composite score (-1 to +1)",
    )
    combined_matrix_score = models.DecimalField(
        max_digits=5, decimal_places=4, default=0,
        help_text="Final matrix score combining GEC + ATR borders + ATR filter",
    )

    # Sub-scores
    momentum_score = models.DecimalField(max_digits=5, decimal_places=4, default=0)
    trend_score = models.DecimalField(max_digits=5, decimal_places=4, default=0)
    volatility_score = models.DecimalField(max_digits=5, decimal_places=4, default=0)
    dxy_correlation_score = models.DecimalField(max_digits=5, decimal_places=4, default=0)

    # ATR context
    atr_border_layer = models.IntegerField(
        default=0,
        help_text="Which ATR border layer the price is in (0=innermost, 3=outermost)",
    )
    atr_ratio = models.DecimalField(
        max_digits=6, decimal_places=4, default=0,
        help_text="Current ATR / ATR SMA ratio",
    )
    atr_filter_pass = models.BooleanField(
        default=False,
        help_text="Whether ATR ratio is within the ideal entry range",
    )

    # Price levels
    entry_price = models.DecimalField(max_digits=20, decimal_places=6, blank=True, null=True)
    stop_loss = models.DecimalField(max_digits=20, decimal_places=6, blank=True, null=True)
    take_profit = models.DecimalField(max_digits=20, decimal_places=6, blank=True, null=True)
    risk_reward_ratio = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)

    # Metadata
    confidence = models.DecimalField(max_digits=5, decimal_places=2, default=50)
    is_active = models.BooleanField(default=True)
    generated_by = models.CharField(max_length=50, default="gold_edge_engine")

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["symbol", "timeframe", "-created_at"]),
            models.Index(fields=["direction", "is_active"]),
        ]

    def __str__(self):
        return (
            f"GoldEdge {self.direction} {self.symbol.name} "
            f"({self.timeframe.code}) — GEC={self.gec_score}"
        )


class GoldEdgeBacktest(models.Model):
    """
    Backtest results specific to the Gold Edge strategy.
    """

    STATUS_CHOICES = [
        ("PENDING", "Pending"),
        ("RUNNING", "Running"),
        ("COMPLETED", "Completed"),
        ("FAILED", "Failed"),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="gold_edge_backtests",
    )
    config = models.ForeignKey(
        GoldEdgeConfig,
        on_delete=models.SET_NULL,
        null=True,
        related_name="backtests",
    )
    name = models.CharField(max_length=200)
    status = models.CharField(max_length=15, choices=STATUS_CHOICES, default="PENDING")

    # Time range
    start_date = models.DateField()
    end_date = models.DateField()

    # Results
    initial_balance = models.DecimalField(max_digits=20, decimal_places=2, default=10000)
    final_balance = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    total_pnl = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    total_pnl_percent = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    total_trades = models.IntegerField(default=0)
    winning_trades = models.IntegerField(default=0)
    losing_trades = models.IntegerField(default=0)
    win_rate = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    profit_factor = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    max_drawdown = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    sharpe_ratio = models.DecimalField(max_digits=10, decimal_places=4, default=0)

    # Detailed data
    parameters = models.JSONField(default=dict)
    trades = models.JSONField(default=list)
    equity_curve = models.JSONField(default=list)
    gec_scores_over_time = models.JSONField(
        default=list,
        help_text="GEC composite score at each bar for analysis",
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"GoldEdge BT: {self.name} — {self.status}"
