# Generated by Django 4.2.30 on 2026-08-27 09:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfluenceScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('m5_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('m15_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('m30_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('h1_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('h2_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('h4_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short'), ('NEUTRAL', 'Neutral')], default='NEUTRAL', max_length=10)),
                ('higher_tf_agreement', models.BooleanField(default=False)),
                ('all_tf_aligned', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signal_type', models.CharField(choices=[('STRONG_BUY', 'Strong Buy'), ('BUY', 'Buy'), ('NEUTRAL', 'Neutral'), ('SELL', 'Sell'), ('STRONG_SELL', 'Strong Sell')], max_length=20)),
                ('strength', models.DecimalField(decimal_places=2, max_digits=5)),
                ('confluence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('indicator_agreement', models.JSONField(default=dict)),
                ('pattern_detected', models.CharField(blank=True, max_length=100)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('risk_reward_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('h4_trend', models.CharField(blank=True, max_length=10)),
                ('h1_trend', models.CharField(blank=True, max_length=10)),
                ('m15_trend', models.CharField(blank=True, max_length=10)),
                ('mtf_confluence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('generated_by', models.CharField(default='system', max_length=50)),
                ('confidence', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('WIN', 'Win'), ('LOSS', 'Loss'), ('BREAKEVEN', 'Breakeven'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('actual_pips', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_favorable', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_adverse', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='signals.signal')),
            ],
            options={
                'ordering': ['-closed_at'],
            },
        ),
    ]
